server:
  port: 80
knife4j:
  gateway:
    enabled: true # 开启gateway聚合组件
    strategy: discover # 聚合模式采用discover服务发现的模式
    discover:
      enabled: true # 开启discover模式
      version: swagger2 # 聚合子服务全部为swagger2规范的文档
      excluded-services:
        - gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-user-route
          uri: lb://service-user
          predicates:
            - Path=/front/user/**
          filters:
            - StripPrefix=2
        - id: service-goods-route
          uri: lb://service-goods
          predicates:
            - Path=/front/goods/**
          filters:
            - StripPrefix=2
        - id: service-test-route
          uri: lb://test
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
        - id: service-test2-route
          uri: lb://test2
          predicates:
            - Path=/test2/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding: true
freeUrls:
  url: v2,/login,/register/code